name: 'Wiz-CLI Action'
description: 'Downloads the wiz-cli binary, authenticates to the UAL Wiz instance, and then runs a image scan on supplied image in local registry.'
inputs:
  image-to-scan:  # id of input
    description: 'Image that should be scanned prior to deployment in local registry. Include registry, name, and tag of image.'
    required: true
  wiz-access-key:
    description: 'Access key for Wiz authentication.'
    required: true
  wiz-secret-key:
    description: 'Secret key for Wiz authentication.'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-wiz
      run: curl -o wizcli https://wizcli.app.wiz.io/wizcli; chmod +x wizcli
      shell: bash
    - id: authenticate-to-wiz
      run: ./wizcli auth --id "${{ inputs.wiz-access-key }}" --secret "${{ inputs.wiz-secret-key }}"
      shell: bash
    - id: run-image-scan
      run: ./wizcli iac scan --path ${{ inputs.image-to-scan }}
      shell: bash
